## Import Pandas and use its read_csv function to read CSV files.

In [1]:
import pandas as pd

poke_df = pd.read_csv('pokemon_data.csv')
poke_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

## Reading data in pandas

In [2]:
## Read first 5 rows of poke_df
print(f"The first 5 rows inside poke_df:")
poke_df.head(5)

The first 5 rows inside poke_df:

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [3]:
## Read the columns
print(f"The columns inside poke_df: \n")
print(list(poke_df.columns))    # poke_df.columns returns index object with list inside. Type cast it into a list if you want.

The columns inside poke_df:

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']

In [4]:
## Read each column (reading each row inside name column)
print(f"The rows inside column 'Name' are: \n")
poke_df['Name']

The rows inside column 'Name' are:

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [5]:
## Read multiple columns
print(f"The rows inside the Name, Type 1 and HP columns: \n")
poke_df[['Name', 'Type 1', 'HP']]

The rows inside the Name, Type 1 and HP columns:

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [6]:
## Read a specific row
print(f"The first row contains the following information:\n")
poke_df.iloc[0]  # returns every data inside that row

The first row contains the following information:

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object

In [7]:
## Read a specific number of rows
print("The rows with row index 1 to row index 3 are as follows:")
poke_df.iloc[1:4]    # Prints out rows with index 1 to 3, 4 and above are excluded from the list

The rows with row index 1 to row index 3 are as follows:

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [8]:
## Read a specific location
print(f"At the 2nd row index (3rd row), 1st column index (2nd column): {poke_df.iloc[2,1]}")
poke_df.iloc[2,1]  # returns whatever data is inside

At the 2nd row index (3rd row), 1st column index (2nd column): Venusaur

'Venusaur'

## TIP: Iterating through the dataframe (or dataset or whatever)

In [9]:
## First way: Using loops to iterate with the help of .iterrows() function

#for index, row in poke_df.iterrows():   # IMPORTANT: Useful if you want a pointer iterating across the dataset.
    #print(index, row)                   # This will print out complete string information across each row
    #print(index, row['Name'])           # This will print out the Name column only (along with their respective index)
    
# Instead of manually iterating through the rows using for loop (for loops are still useful though)
# This is only useful if you want to separate one group of data and appending it to another dataframe or set
# or if you just want to print the specific group inside a column
# You can use multiple conditions inside loc[]
poke_df.loc[poke_df['Type 1'] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

## Describing data

In [10]:
poke_df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

## Sorting data

In [11]:
# Sorting the data frame using Names in ascending order
poke_df = poke_df.sort_values('Name')
poke_df

# Sorting the data frame using Names in descending order
poke_df = poke_df.sort_values('Name', ascending=False)
poke_df

# Sorting the data frame using multiple columns, with the Type 1 column being
# in ascending order while the HP being in descending order.
# IMPORTANT: This code is useful for categorical columns (or those with foreign key columns)
poke_df = poke_df.sort_values(['Type 1', 'HP'], ascending=[True, False])
poke_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
97,90,Shellder,Water,NaN,30,65,100,45,25,40,1,False
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

## Making changes to the data

In [14]:
# One way of adding columns and adding the result to
# a new column. This is the safer way.

poke_df['Total'] = (poke_df['HP'] + poke_df['Attack'] + poke_df['Defense'] + poke_df['Sp. Atk'] + 
                    poke_df['Sp. Def'] + poke_df['Speed'])
poke_df.head(5)


# Another way of adding columns and adding the result to
# a new column. WARNING: ITS DANGEROUS. USE AT YOUR OWN RISK

# Axis = 1: Horizontally; Row
# Axis = 0: Vertically; Column
'''
poke_df['Total'] = poke_df.iloc[:, 4:10].sum(axis=1)
'''
# One way of Reordering columns. USE AT OWN RISK
'''
cols_reorder = list(poke_df.columns.values)
poke_df = poke_df[cols_reorder[0:4] + cols_reorder[5:11] + [cols_reorder[4]] +
                 cols_reorder[11:13]]
'''
# A better way of Reordering columns.
poke_df = poke_df[['#', 'Name', 'Type 1','Type 2', 'HP', 'Attack', 'Defense',
                  'Sp. Atk', 'Sp. Def', 'Speed', 'Total', 
                  'Generation', 'Legendary']]

poke_df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,515,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,550,5,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,411,6,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,600,2,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,500,2,False

# Dropping a column

In [15]:
# If you wanna drop a specific column
'''
poke_df = poke_df.drop(columns=['Total'])
poke_df.head(5)
'''

"\npoke_df = poke_df.drop(columns=['Total'])\npoke_df.head(5)\n"

## Export into desired format

In [17]:
# This exports into .csv (Comma Separated Values) format WITH INDEX.
'''
poke_df.to_csv('modified-poke-data.csv')
'''
# Pass an index=False parameter inside the index inside the exported file
'''
poke_df.to_csv('modified-poke-data.csv', index=False)
'''
# Pass a sep='\t' separator parameter inside if you want the csv file
# to be separated by tabs instead of commas
'''
poke_df.to_csv('modified-poke-data.csv', index=False, sep='\t')
'''
# Same goes for the txt format
'''
poke_df.to_csv('modified-poke-data.txt', index=False, sep='\t')
'''
# Exporting into xlsx (Excel) format.
'''
poke_df.to_excel('modified-poke-data.xlsx', index=False)
'''

# Filtering Data

In [20]:
# Output only the rows with type 1 == Grass
poke_df.loc[poke_df['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,531,6,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,464,5,False
516,465,Tangrowth,Grass,NaN,100,100,125,110,50,50,535,4,False
551,492,ShayminSky Forme,Grass,Flying,100,103,75,120,75,127,600,4,True
550,492,ShayminLand Forme,Grass,NaN,100,100,100,100,100,100,600,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,273,Seedot,Grass,NaN,40,40,50,30,30,30,220,3,False
606,546,Cottonee,Grass,Fairy,40,27,60,37,50,66,280,5,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,280,4,False
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,250,2,False
206,191,Sunkern,Grass,NaN,30,30,30,30,30,30,180,2,False

In [26]:
# Output rows with Type 1 grass and type 2 poison
poke_df.loc[(poke_df['Type 1'] == 'Grass') &
            (poke_df['Type 2'] == 'Poison') &
           (poke_df['HP'] > 70)]
# Make sure the 2 conditions are separated by parentheses
# Also the conditional operators inside pandas parameters should be:
# & for and; | for or

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,464,5,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,490,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,490,1,False

In [36]:
# Copy these values to another dataframe:
grass_poison_hp70 = poke_df.loc[(poke_df['Type 1'] == 'Grass') &
            (poke_df['Type 2'] == 'Poison') &
           (poke_df['HP'] > 70)]

grass_poison_hp70

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,464,5,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,490,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,490,1,False

However, the index of the new dataframe are preserved from its parent dataframe.

In [37]:
# To reset index
grass_poison_hp70.reset_index(drop=True, inplace=True)
grass_poison_hp70

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
0,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,464,5,False
1,71,Victreebel,Grass,Poison,80,105,65,100,70,70,490,1,False
2,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
3,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
4,45,Vileplume,Grass,Poison,75,80,85,110,90,50,490,1,False

In [38]:
# You can export the new dataframe into a csv file as a checkpoint
grass_poison_hp70.to_csv('grass-poison-hp70.csv', index=False)

Returning to the poke_df dataframe:

In [39]:
# If you want to retain only the 'mega' pokemons:
poke_df.loc[poke_df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,600,2,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,600,2,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,600,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,495,1,False
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,600,2,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,565,3,False
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,480,3,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,700,4,False
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,780,3,True
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,700,3,False
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,700,3,True
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,700,3,True
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,590,3,False
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,610,2,False
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,575,3,False
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,625,4,False
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,510,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,630,3,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,560,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,555,3,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,600,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,594,4,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,525,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,630,3,False
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,580,3,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,590,1,False
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,545,5,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,579,1,False
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,580,4,False
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,780,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,780,1,True
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,618,3,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,618,4,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,590,1,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,700,2,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,615,1,False
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,700,6,True
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,700,3,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,610,2,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,630,3,False
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,480,3,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,635,3,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,590,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,640,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,630,1,False
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,560,3,False

In [40]:
# If you want to filter out 'Mega' name:
poke_df.loc[~poke_df['Name'].str.contains('Mega')]
# ~ (tilde) is a NOT conditional operator

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,515,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,550,5,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,411,6,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,500,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,495,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,90,Shellder,Water,NaN,30,65,100,45,25,40,305,1,False
106,98,Krabby,Water,NaN,30,105,90,25,25,50,325,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,295,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,200,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,200,3,False

In [41]:
# If you want to get the fire and grass type pokemons only
# You can use regex:
import re

poke_df.loc[poke_df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]
# flags=re.I means ignore capitalization
# regex=True means you enable regex symbols/functions inside the contains function

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
263,244,Entei,Fire,NaN,115,115,85,90,75,100,580,2,True
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,528,5,False
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,680,2,True
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,540,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,480,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,273,Seedot,Grass,NaN,40,40,50,30,30,30,220,3,False
606,546,Cottonee,Grass,Fairy,40,27,60,37,50,66,280,5,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,280,4,False
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,250,2,False
206,191,Sunkern,Grass,NaN,30,30,30,30,30,30,180,2,False

In [42]:
# If you want to find out all the pokemon names that contain the
# string sequence: "pi"
poke_df.loc[poke_df['Name'].str.contains('pi[a-z]*', flags=re.I, regex=True)]
# [a-z] range of letters from a to z
# asterisk (*) at the end means whatever sequence of [a-z] from zero to
# infinite amount of characters

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,474,4,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,600,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,500,1,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,290,2,False
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,195,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,250,2,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,320,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,205,2,False
189,175,Togepi,Fairy,NaN,35,20,65,40,65,20,245,2,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,418,5,False
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,308,5,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,500,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,299,1,False
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,485,4,False
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,460,3,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,390,1,False
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,313,6,False
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,250,2,False
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,290,3,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,450,2,False
716,648,MeloettaPirouette Forme,Normal,Fighting,100,128,90,77,77,128,600,5,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,220,4,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,579,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,479,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,349,1,False
358,327,Spinda,Normal,NaN,60,60,60,60,60,60,360,3,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,264,5,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,251,1,False
345,316,Gulpin,Poison,NaN,70,43,53,43,53,40,302,3,False
502,452,Drapion,Poison,Dark,70,90,110,60,75,95,500,4,False
501,451,Skorupi,Poison,Bug,40,50,90,30,55,65,330,4,False
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,470,3,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,410,2,False
596,536,Palpitoad,Water,Ground,75,65,55,65,55,69,384,5,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,314,4,False

In [43]:
# If you want to find every pokemon that has a name that starts with
# 'pi'
poke_df.loc[poke_df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,600,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,500,1,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,290,2,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,320,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,205,2,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,418,5,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,450,2,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,579,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,479,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,349,1,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,264,5,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,251,1,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,314,4,False

## Conditional Changes

Change every existence of the word 'Fire' inside column Type 1 into 'Flamer'

In [47]:
poke_df.loc[poke_df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'
poke_df.loc[poke_df['Type 1'] == 'Flamer']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
263,244,Entei,Flamer,NaN,115,115,85,90,75,100,580,2,True
559,500,Emboar,Flamer,Fighting,110,123,65,100,65,65,528,5,False
270,250,Ho-oh,Flamer,Flying,106,130,90,110,154,90,680,2,True
616,555,DarmanitanZen Mode,Flamer,Psychic,105,30,105,140,105,55,540,5,False
615,555,DarmanitanStandard Mode,Flamer,NaN,105,140,55,30,55,95,480,5,False
542,485,Heatran,Flamer,Steel,91,90,106,130,106,77,600,4,True
558,499,Pignite,Flamer,Fighting,90,93,55,70,55,55,418,5,False
158,146,Moltres,Flamer,Flying,90,100,90,125,85,90,580,1,True
64,59,Arcanine,Flamer,NaN,90,110,80,100,80,95,555,1,False
736,668,Pyroar,Flamer,Normal,86,68,72,109,66,106,507,6,False
692,631,Heatmor,Flamer,NaN,85,97,66,105,66,65,484,5,False
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,600,6,True
279,257,BlazikenMega Blaziken,Flamer,Fighting,80,160,80,130,80,100,630,3,False
278,257,Blaziken,Flamer,Fighting,80,120,70,110,70,80,530,3,False
171,157,Typhlosion,Flamer,NaN,78,84,78,109,85,100,534,2,False
731,663,Talonflame,Flamer,Flying,78,81,71,74,69,126,499,6,False
8,6,CharizardMega Charizard Y,Flamer,Flying,78,104,78,159,115,100,634,1,False
7,6,CharizardMega Charizard X,Flamer,Dragon,78,130,111,130,85,100,634,1,False
6,6,Charizard,Flamer,Flying,78,84,78,109,85,100,534,1,False
437,392,Infernape,Flamer,Fighting,76,104,71,104,71,108,534,4,False
573,514,Simisear,Flamer,NaN,75,98,63,98,63,101,498,5,False
518,467,Magmortar,Flamer,NaN,75,95,67,125,95,83,540,4,False
723,655,Delphox,Flamer,Psychic,75,69,72,114,100,104,534,6,False
43,38,Ninetales,Flamer,NaN,73,76,75,81,100,100,505,1,False
355,324,Torkoal,Flamer,NaN,70,85,140,85,70,20,470,3,False
614,554,Darumaka,Flamer,NaN,70,90,45,15,45,50,315,5,False
354,323,CameruptMega Camerupt,Flamer,Ground,70,120,100,145,105,20,560,3,False
353,323,Camerupt,Flamer,Ground,70,100,70,105,75,40,460,3,False
557,498,Tepig,Flamer,NaN,65,63,45,45,45,45,308,5,False
84,78,Rapidash,Flamer,NaN,65,100,70,80,80,105,500,1,False
135,126,Magmar,Flamer,NaN,65,95,57,100,85,93,495,1,False
147,136,Flareon,Flamer,NaN,65,130,60,95,110,65,525,1,False
436,391,Monferno,Flamer,Fighting,64,78,52,78,52,81,405,4,False
735,667,Litleo,Flamer,Normal,62,50,58,73,54,72,369,6,False
730,662,Fletchinder,Flamer,Flying,62,73,55,56,52,84,382,6,False
352,322,Numel,Flamer,Ground,60,60,40,65,45,35,305,3,False
277,256,Combusken,Flamer,Fighting,60,85,60,85,60,55,405,3,False
722,654,Braixen,Flamer,NaN,59,59,58,90,70,73,409,6,False
170,156,Quilava,Flamer,NaN,58,64,58,80,65,80,405,2,False
5,5,Charmeleon,Flamer,NaN,58,64,58,80,65,80,405,1,False
63,58,Growlithe,Flamer,NaN,55,70,45,70,50,60,350,1,False
83,77,Ponyta,Flamer,NaN,50,85,55,65,65,90,410,1,False
572,513,Pansear,Flamer,NaN,50,53,48,53,48,64,316,5,False
237,219,Magcargo,Flamer,Rock,50,50,120,80,80,30,410,2,False
276,255,Torchic,Flamer,NaN,45,60,40,70,50,45,310,3,False
259,240,Magby,Flamer,NaN,45,75,37,70,55,83,365,2,False
435,390,Chimchar,Flamer,NaN,44,58,44,58,44,61,309,4,False
236,218,Slugma,Flamer,NaN,40,40,40,70,40,20,250,2,False
721,653,Fennekin,Flamer,NaN,40,45,40,62,60,60,307,6,False
169,155,Cyndaquil,Flamer,NaN,39,52,43,60,50,65,309,2,False
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,309,1,False
42,37,Vulpix,Flamer,NaN,38,41,40,50,65,65,299,1,False

If you want to change 'Flamer' back to 'Fire'

In [49]:
poke_df.loc[poke_df['Type 1'] == 'Flamer', 'Type 1'] = 'Fire'
poke_df.loc[poke_df['Type 1'] == 'Fire']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
263,244,Entei,Fire,NaN,115,115,85,90,75,100,580,2,True
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,528,5,False
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,680,2,True
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,540,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,480,5,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,600,4,True
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,418,5,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,580,1,True
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,555,1,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,507,6,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,484,5,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,630,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,530,3,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,534,2,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,499,6,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,534,1,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,534,4,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,498,5,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,540,4,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,534,6,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,505,1,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,470,3,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,315,5,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,560,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,460,3,False
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,308,5,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,500,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,495,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,525,1,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,405,4,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,369,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,382,6,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,305,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,405,3,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,409,6,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,405,2,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,350,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,410,1,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,316,5,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,410,2,False
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,310,3,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,365,2,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,309,4,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,250,2,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,307,6,False
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,309,2,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,299,1,False

If you want to change all Fire pokemon Legendary status to True
Set up a test dataframe since we don't want to screw up the actual dataframe

In [51]:
test_df = poke_df
test_df.loc[test_df['Type 1'] == 'Fire', 'Legendary'] = True
test_df.loc[test_df['Type 1'] == 'Fire']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
263,244,Entei,Fire,NaN,115,115,85,90,75,100,580,2,True
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,528,5,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,680,2,True
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,540,5,True
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,480,5,True
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,600,4,True
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,418,5,True
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,580,1,True
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,555,1,True
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,507,6,True
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,484,5,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,630,3,True
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,530,3,True
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,534,2,True
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,499,6,True
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,True
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1,True
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,534,1,True
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,534,4,True
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,498,5,True
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,540,4,True
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,534,6,True
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,505,1,True
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,470,3,True
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,315,5,True
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,560,3,True
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,460,3,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,308,5,True
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,500,1,True
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,495,1,True
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,525,1,True
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,405,4,True
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,369,6,True
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,382,6,True
352,322,Numel,Fire,Ground,60,60,40,65,45,35,305,3,True
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,405,3,True
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,409,6,True
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,405,2,True
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1,True
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,350,1,True
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,410,1,True
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,316,5,True
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,410,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,310,3,True
259,240,Magby,Fire,NaN,45,75,37,70,55,83,365,2,True
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,309,4,True
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,250,2,True
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,307,6,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,309,2,True
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,True
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,299,1,True

In [ ]:
poke_df = pd.read_csv('modified-poke-data.csv')    # Reset the test_df
test_df = poke_df

If you want to change the legendary status and generation number of all pokemon with total stat number of above 500 into 'TEST VALUE'

In [52]:
test_df.loc[test_df['Total'] > 500, ['Generation', 'Legendary']] = 'TEST VALUE'
test_df.loc[test_df['Legendary'] == 'TEST VALUE']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,515,TEST VALUE,TEST VALUE
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,550,TEST VALUE,TEST VALUE
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,600,TEST VALUE,TEST VALUE
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,600,TEST VALUE,TEST VALUE
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,600,TEST VALUE,TEST VALUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,230,Kingdra,Water,Dragon,75,95,95,95,95,85,540,TEST VALUE,TEST VALUE
726,658,Greninja,Water,Dark,72,95,67,103,71,122,530,TEST VALUE,TEST VALUE
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,560,TEST VALUE,TEST VALUE
130,121,Starmie,Water,Psychic,60,75,85,100,85,115,520,TEST VALUE,TEST VALUE
98,91,Cloyster,Water,Ice,50,95,180,85,45,70,525,TEST VALUE,TEST VALUE

If you want to change the generation and legendary value of every pokemon with total stat number of above 500 into:
Test 1 for Generation column
Test 2 for Legendary column

In [53]:
test_df.loc[test_df['Total'] > 500, ['Generation', 'Legendary']] = ['Test 1','Test 2']
test_df.loc[test_df['Legendary'] == 'Test 2']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,515,Test 1,Test 2
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,550,Test 1,Test 2
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,600,Test 1,Test 2
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,600,Test 1,Test 2
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,600,Test 1,Test 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,230,Kingdra,Water,Dragon,75,95,95,95,95,85,540,Test 1,Test 2
726,658,Greninja,Water,Dark,72,95,67,103,71,122,530,Test 1,Test 2
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,560,Test 1,Test 2
130,121,Starmie,Water,Psychic,60,75,85,100,85,115,520,Test 1,Test 2
98,91,Cloyster,Water,Ice,50,95,180,85,45,70,525,Test 1,Test 2

In [54]:
poke_df = pd.read_csv('modified-poke-data.csv')    # Reset the test_df
test_df = poke_df

## Aggregate Statistics (groupby function)
poke_df is a dataframe. You can group it accordingly using groupby('column_name') function. If you want to group it according to multiple columns, use DataFrame.groupby(['column_name1','column_name2'])

Grouping by Type 1 and finding the mean of each type 1 then sorting their values by Defense in descending order to find out which type of pokemon has the highest amount of Defense

In [55]:
poke_df.groupby(['Type 1']).mean().sort_values('Defense', ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total
Type 1,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,487.703704
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,453.750000
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,550.531250
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,437.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,439.562500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,430.455357
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,433.458333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,421.142857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,378.927536
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,445.741935
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,399.142857
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,458.076923
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,475.947368
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,443.409091
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,485.000000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,416.444444
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,413.176471
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,401.683673

Establishing a count column and grouping by Type 1 and finding the total number of pokemons inside each Type 1

In [69]:
poke_df['count'] = 1
poke_df.groupby(['Type 1']).count()['count']
# It does not count rows with NaN (null type values)

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

If you want to group it by multiple columns:

In [71]:
poke_df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64