## Small Recap with Pandas

In [5]:
import pandas as pd

df = pd.read_csv('fruits.csv')
df

    fruit  price  quantity
0   Apple      4        10
1    Pear      7        14
2  Durian     10         2

## Datatypes:

#### Lists, DataFrames and Series

In [6]:
df.loc[:, 'fruit']

0     Apple
1      Pear
2    Durian
Name: fruit, dtype: object

In [7]:
df[df['fruit']== 'Apple']

   fruit  price  quantity
0  Apple      4        10

In [8]:
df[df['fruit'] != 'Pear']

    fruit  price  quantity
0   Apple      4        10
2  Durian     10         2

In [9]:
df[df['price'] > 6]

    fruit  price  quantity
1    Pear      7        14
2  Durian     10         2

In [10]:
cheap_fruits = df[df['price'] < 8]
cheap_fruits['fruit']

0    Apple
1     Pear
Name: fruit, dtype: object

In [11]:
exp_fruit_df = df[~df['fruit'].isin(cheap_fruits['fruit'])]
exp_fruit_df

    fruit  price  quantity
2  Durian     10         2

## Importing Data

In [12]:
chat_df = pd.read_csv('Chats.csv')
chat_df

,Unnamed: 0,message_id,timestamp,agent,buyer_userid,conversation_id,shopid,Date,is_buyer,is_seller,content,conversation_status,photo_img,order_time
0,0,1,2020-04-04 11:20:48,NO AGENT,B898484520,C100307556080880867,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 10:54:01
1,1,2,2020-04-04 19:59:30,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 18:10:07
2,2,3,2020-04-04 19:59:37,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07
3,3,4,2020-04-04 19:59:37,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07
4,4,5,2020-04-04 19:59:47,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18813,18831,18832,2020-04-04 07:47:00,Exeter,B898227517,C99203736600906979,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 07:13:45
18814,18832,18833,2020-04-04 07:47:02,Exeter,B898227517,C99203736600906979,S1076522480,2020-04-04,False,True,"{""url"":""https://seller.shopee.co.id/webview/ra...",normal,NO IMG,2020-04-04 07:13:45
18815,18833,18834,2020-04-04 20:09:20,NO AGENT,B898300556,C99517436717239523,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 20:09:20
18816,18834,18835,2020-04-04 20:10:12,NO AGENT,B898300556,C99517436717239523,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 20:09:20
18817,18835,18836,2020-04-04 14:24:18,NO AGENT,B898393996,C99918758461377763,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 13:59:07

# Using PivotTable

### How many messagees are attributed to each Shopee shop?

In [14]:
chat_pivot = chat_df.pivot_table(index='shopid', values='message_id', aggfunc='count')
chat_pivot.sort_values('message_id', ascending=False).reset_index()

        shopid  message_id
0  S1076522480        8390
1   S963262026        5480
2   S881169418        2093
3   S952055895        1330
4   S899521933         630
5   S975779742         389
6  S1003242176         328
7  S1073211457         170
8  S1003883202           6
9   S959767657           2

### How many messages each buyer sent in or receive in total?

In [20]:
top_buyers = chat_df.pivot_table(index='buyer_userid', values='message_id', aggfunc='count')
top_buyers = top_buyers.sort_values('message_id', ascending=False).reset_index()

### Remove from the dataset, messages from the top 3 buyers by messages?

In [22]:
top_3_buyers = top_buyers.head(3)
top_3_buyers

  buyer_userid  message_id
0  B1044578418         117
1  B1074756650          82
2   B919227320          80

In [25]:
chat_df = chat_df[~chat_df['buyer_userid'].isin(top_3_buyers['buyer_userid'])]

# Check new buyers
top_buyers = chat_df.pivot_table(index='buyer_userid', values='message_id', aggfunc='count')
top_buyers = top_buyers.sort_values('message_id', ascending=False)

In [28]:
top_buyers.head(3)

              message_id
buyer_userid
B900975539            73
B951568686            67
B1121411138           65

## Workshop Question (1)

In [30]:
# Use convers.csv for a smaller table
chat_df = pd.read_csv('Chats.csv')
test_df = chat_df[chat_df['conversation_id'] == 'C249977464015359203']
test_df

,Unnamed: 0,message_id,timestamp,agent,buyer_userid,conversation_id,shopid,Date,is_buyer,is_seller,content,conversation_status,photo_img,order_time
3061,3071,3072,2020-04-04 21:09:13,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3062,3072,3073,2020-04-04 21:09:30,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3063,3073,3074,2020-04-04 21:09:34,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3064,3074,3075,2020-04-04 21:09:41,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3065,3075,3076,2020-04-04 21:12:57,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3066,3076,3077,2020-04-04 21:12:58,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,"{""url"":""https://seller.shopee.co.id/webview/ra...",normal,NO IMG,2020-04-04 16:07:30
3067,3077,3078,2020-04-04 21:29:23,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,True,False,Some Random Text,closed,NO IMG,2020-04-04 16:07:30
3068,3078,3079,2020-04-04 21:30:14,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3069,3079,3080,2020-04-04 21:30:17,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3070,3080,3081,2020-04-04 21:32:57,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30
3071,3081,3082,2020-04-04 22:08:16,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,True,False,Some Random Text,closed,NO IMG,2020-04-04 16:07:30
3072,3082,3083,2020-04-04 22:08:57,Worcester,B933332261,C249977464015359203,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 16:07:30

In [49]:
def assign_session(df):
    session_number = 1
    
    # create an empty list to store the session numbers
    session_list = []
    for ind, row in df.iterrows():
        session_list.append(session_number)
        # if the value of conversation status is closed.
        if row['conversation_status'] == 'closed':
            session_number += 1
    df['session'] = session_list
    
    return df

In [50]:
chat_df.groupby('conversation_id')
# create an answer_list
answer_list = []
for ind, df in chat_df.groupby('conversation_id'):
    # run the function return a dataframe
    df = assign_session(df)
    
    # list will have a list of dataframes
    answer_list.append(df)

answer_df = pd.concat(answer_list)

C:\Users\KRISTIAN\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [51]:
answer_df

,Unnamed: 0,message_id,timestamp,agent,buyer_userid,conversation_id,shopid,Date,is_buyer,is_seller,content,conversation_status,photo_img,order_time,session
0,0,1,2020-04-04 11:20:48,NO AGENT,B898484520,C100307556080880867,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 10:54:01,1
1,1,2,2020-04-04 19:59:30,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 18:10:07,1
2,2,3,2020-04-04 19:59:37,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,1
3,3,4,2020-04-04 19:59:37,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,1
4,4,5,2020-04-04 19:59:47,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18813,18831,18832,2020-04-04 07:47:00,Exeter,B898227517,C99203736600906979,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 07:13:45,1
18814,18832,18833,2020-04-04 07:47:02,Exeter,B898227517,C99203736600906979,S1076522480,2020-04-04,False,True,"{""url"":""https://seller.shopee.co.id/webview/ra...",normal,NO IMG,2020-04-04 07:13:45,1
18815,18833,18834,2020-04-04 20:09:20,NO AGENT,B898300556,C99517436717239523,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 20:09:20,1
18816,18834,18835,2020-04-04 20:10:12,NO AGENT,B898300556,C99517436717239523,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 20:09:20,1
18817,18835,18836,2020-04-04 14:24:18,NO AGENT,B898393996,C99918758461377763,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 13:59:07,1

## Workshop Question (2)

How long will the seller reply to the first message of the buyer?

In [70]:
all_df = []

chat_df['timestamp'] = pd.to_datetime(chat_df['timestamp'])

# get session id by combining conversation id and message id
chat_df['session_id'] = chat_df['conversation_id'].astype(str) + "_" + answer_df['session'].astype(str)

for ind, df in chat_df.groupby('session_id'):
    df = df.sort_values('timestamp')
    # get a dataframe of only buyers
    buyer_df = df[df['is_buyer']]
    if len(buyer_df) == 0:
        # outbound
        df['first_reply_time'] = -2
    else:
        # get earliest message from buyer
        earliest_buyer_message = buyer_df['timestamp'].min()
        
        # filter out seller messages that are before the earliest buyer message
        
        seller_timing = df[df['is_seller']]
        seller_timing = seller_timing[seller_timing['timestamp'] > earliest_buyer_message]
        
        if len(seller_timing) == 0:
            #no reply backlog
            df['first_reply_time'] = -1
        
        else:
            seller_earliest = seller_timing['timestamp'].min()
            time_diff = seller_earliest - earliest_buyer_message
            df['first_reply_time'] = time_diff.seconds
    all_df.append(df)

chat_df = pd.concat(all_df)

C:\Users\KRISTIAN\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\KRISTIAN\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [72]:
chat_df.head(15)

,Unnamed: 0,message_id,timestamp,agent,buyer_userid,conversation_id,shopid,Date,is_buyer,is_seller,content,conversation_status,photo_img,order_time,session_id,first_reply_time
0,0,1,2020-04-04 11:20:48,NO AGENT,B898484520,C100307556080880867,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 10:54:01,C100307556080880867_1,-1
1,1,2,2020-04-04 19:59:30,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 18:10:07,C102737304979573987_1,-1
2,2,3,2020-04-04 19:59:37,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
3,3,4,2020-04-04 19:59:37,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
4,4,5,2020-04-04 19:59:47,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
5,5,6,2020-04-04 19:59:47,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
6,6,7,2020-04-04 19:59:56,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
7,7,8,2020-04-04 19:59:56,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
8,8,9,2020-04-04 19:59:59,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
9,9,10,2020-04-04 19:59:59,NO AGENT,B899050240,C102737304979573987,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 18:10:07,C102737304979573987_1,-1
10,10,11,2020-04-04 14:10:20,NO AGENT,B899186193,C103321218668367075,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 13:54:44,C103321218668367075_1,-1
11,11,12,2020-04-04 19:51:14,Beauregard,B899197356,C103369163388292323,S1076522480,2020-04-04,True,False,Some Random Text,normal,"<img class=""gb_4b"" src=""www.shopeeprod.com/pid...",2020-04-04 19:04:37,C103369163388292323_1,-1
12,12,13,2020-04-04 19:51:14,Beauregard,B899197356,C103369163388292323,S1076522480,2020-04-04,True,False,Some Random Text,closed,NO IMG,2020-04-04 19:04:37,C103369163388292323_1,-1
19,19,20,2020-04-04 19:51:10,NO AGENT,B899197356,C103369163388292323,S1076522480,2020-04-04,True,False,Some Random Text,normal,NO IMG,2020-04-04 19:04:37,C103369163388292323_2,575
13,13,14,2020-04-04 20:00:45,Beauregard,B899197356,C103369163388292323,S1076522480,2020-04-04,False,True,Some Random Text,normal,NO IMG,2020-04-04 19:04:37,C103369163388292323_2,575

In [ ]:
chat_df.drop_duplicates['session_id'].loc(:,['session_id','chat_duration','first_reply_time'])